In [2]:
import numpy as np
import pandas as pd

In [3]:
pd.set_option('display.max_columns', 150)

### 시군구 단위 자료 1차 가공
1. 2022 선거 데이터 처리

In [4]:
voting = pd.DataFrame(pd.read_excel("voting_data_2022.xlsx"))

In [5]:
voting.iloc[0:,4:] = voting.iloc[0:,4:].apply(lambda x : pd.to_numeric(x.str.replace(r',','')))
new_vote_2022 = voting[voting['읍면동명']=="합계"]
new_vote_2022['outtotal_2022'] = new_vote_2022.iloc[:,7:18].sum(axis=1)

C:\Users\Popperkim\AppData\Local\Temp\ipykernel_5588\3126311396.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_vote_2022['outtotal_2022'] = new_vote_2022.iloc[:,7:18].sum(axis=1)

In [6]:
new_vote_2022.iloc[:,18] = new_vote_2022.iloc[:,18].replace(0, np.nan)
new_vote_2022['outratio_2022'] = new_vote_2022.iloc[:,21]/new_vote_2022.iloc[:,18]
new_vote_2022.head()

c:\Users\Popperkim\anaconda3\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
C:\Users\Popperkim\AppData\Local\Temp\ipykernel_5588\1376533066.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_vote_2022['outratio_2022'] = new_vote_2022.iloc[:,21]/new_vote_2022.iloc[:,18]

,시도,구시군,읍면동명,투표구명,선거인수,투표수,더불어민주당\n이재명,국민의힘\n윤석열,정의당\n심상정,기본소득당\n오준호,국가혁명당 \n허경영,노동당\n이백윤,새누리당\n옥은호,신자유민주연합\n김경재,우리공화당\n조원진,진보당\n김재연,통일한국당\n이경희,한류연합당\n김민찬,계,무효투표수,기권수,outtotal_2022,outratio_2022
2,서울특별시,종로구,합계,NaN,129968,100629,46130,49172,3115,53,558,42,9,50,82,105,20,30,99366,1263,29339,53236.0,0.535757
85,서울특별시,중구,합계,NaN,111448,84998,38244,42906,2310,46,463,19,10,17,67,57,17,28,84184,814,26450,45940.0,0.545709
164,서울특별시,용산구,합계,NaN,199077,152068,60063,85047,4374,67,755,37,24,56,86,100,27,46,150682,1386,47009,90619.0,0.601392
261,서울특별시,성동구,합계,NaN,252087,197240,84411,103880,5365,123,969,50,20,47,122,152,34,65,195238,2002,54847,110827.0,0.567651
371,서울특별시,광진구,합계,NaN,303582,235471,109922,113733,7072,155,1416,52,36,62,180,172,38,80,232918,2553,68111,122996.0,0.528066

2. 2018 선거 데이터 처리

In [7]:
voting2 = pd.DataFrame(pd.read_excel("voting_data_2018.xlsx"))

In [8]:
new_vote_2018 = voting2[voting2['읍면동명'] == '계']
new_vote_2018['outtotal_2018'] = new_vote_2018.iloc[:,9:16].sum(axis=1)
new_vote_2018.iloc[:,17] = new_vote_2018.iloc[:,17].replace(0, np.nan)
new_vote_2018['outratio_2018'] = new_vote_2018.iloc[:,20]/new_vote_2018.iloc[:,17]

C:\Users\Popperkim\AppData\Local\Temp\ipykernel_5588\4017067436.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_vote_2018['outtotal_2018'] = new_vote_2018.iloc[:,9:16].sum(axis=1)
c:\Users\Popperkim\anaconda3\lib\site-packages\pandas\core\indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
C:\Users\Popperkim\AppData\Local\Temp\ipykernel_5588\4017067436.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_vote_2018['outratio_2018'] = new_vote_2018.iloc[:,20]/new_vote_2018.iloc[:,17]

3. 데이터 병합

In [9]:
new_vote_2022.rename(columns={'구시군':'구시군명'},inplace=True)

c:\Users\Popperkim\anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [10]:
new_vote_2022['구시군명']

2         종로구
85         중구
164       용산구
261       성동구
371       광진구
         ...
22272     산청군
22315     거창군
22365     합천군
22427     제주시
22626    서귀포시
Name: 구시군명, Length: 250, dtype: object

In [11]:
new_vote_2018['구시군명']

2         종로구
57         중구
106       용산구
158       성동구
213       광진구
         ...
11250     산청군
11287     거창군
11327     합천군
11384     제주시
11466    서귀포시
Name: 구시군명, Length: 250, dtype: object

In [12]:
new_vote_2022.rename(columns={'시도':'시도명'},inplace=True)

In [13]:
vote_2018_2022_t = pd.merge(new_vote_2018, new_vote_2022, on = ["구시군명", "시도명"])

In [15]:
vote_2018_2022_t.head()

,선거종류,선거구명,시도명,구시군명,읍면동명_x,구분,선거인수_x,투표수_x,후보자별 득표수,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,무효투표수_x,기권수_x,outtotal_2018,outratio_2018,읍면동명_y,투표구명,선거인수_y,투표수_y,더불어민주당\n이재명,국민의힘\n윤석열,정의당\n심상정,기본소득당\n오준호,국가혁명당 \n허경영,노동당\n이백윤,새누리당\n옥은호,신자유민주연합\n김경재,우리공화당\n조원진,진보당\n김재연,통일한국당\n이경희,한류연합당\n김민찬,계,무효투표수_y,기권수_y,outtotal_2022,outratio_2022
0,NaN,서울특별시,서울특별시,종로구,계,NaN,134963.0,81195.0,41148,18777,15946,1469,358,223,1896,215,59,80091,1104.0,53768.0,38884,0.485498,합계,NaN,129968,100629,46130,49172,3115,53,558,42,9,50,82,105,20,30,99366,1263,29339,53236,0.535757
1,NaN,서울특별시,서울특별시,중구,계,NaN,112336.0,66474.0,34243,15618,12814,1023,279,193,1076,149,96,65491,983.0,45862.0,31152,0.475668,합계,NaN,111448,84998,38244,42906,2310,46,463,19,10,17,67,57,17,28,84184,814,26450,45940,0.545709
2,NaN,서울특별시,서울특별시,용산구,계,NaN,200009.0,116054.0,53964,31073,24074,2151,436,231,2392,226,115,114662,1392.0,83955.0,60583,0.528362,합계,NaN,199077,152068,60063,85047,4374,67,755,37,24,56,86,100,27,46,150682,1386,47009,90619,0.601392
3,NaN,서울특별시,서울특별시,성동구,계,NaN,264634.0,157863.0,84106,34878,30379,2594,689,309,2418,370,123,155866,1997.0,106771.0,71637,0.459606,합계,NaN,252087,197240,84411,103880,5365,123,969,50,20,47,122,152,34,65,195238,2002,54847,110827,0.567651
4,NaN,서울특별시,서울특별시,광진구,계,NaN,308174.0,180373.0,99366,38606,32310,3077,804,376,3222,482,125,178368,2005.0,127801.0,78877,0.442215,합계,NaN,303582,235471,109922,113733,7072,155,1416,52,36,62,180,172,38,80,232918,2553,68111,122996,0.528066

In [16]:
vote_2018_2022_t.columns

Index(['선거종류', '선거구명', '시도명', '구시군명', '읍면동명_x', '구분', '선거인수_x', '투표수_x',
       '후보자별 득표수', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', '무효투표수_x', '기권수_x', 'outtotal_2018', 'outratio_2018',
       '읍면동명_y', '투표구명', '선거인수_y', '투표수_y', '더불어민주당\n이재명', '국민의힘\n윤석열',
       '정의당\n심상정', '기본소득당\n오준호', '국가혁명당 \n허경영', '노동당\n이백윤', '새누리당\n옥은호',
       '신자유민주연합\n김경재', '우리공화당\n조원진', '진보당\n김재연', '통일한국당\n이경희', '한류연합당\n김민찬',
       '계', '무효투표수_y', '기권수_y', 'outtotal_2022', 'outratio_2022'],
      dtype='object')

In [14]:
vote_2018_2022_t.rename(columns={'투표수_x':'2018_total_vote', '투표수_y' : '2022_total_vote', '선거인수_x' : '2018_voter_all', '선거인수_y' : '2022_voter_all'},inplace=True)

In [15]:
vote_2018_2022_sigungu = vote_2018_2022_t[["시도명","구시군명",'2018_total_vote',"outtotal_2018", "outratio_2018",'2022_total_vote', "outtotal_2022","outratio_2022",'2018_voter_all','2022_voter_all']]

In [17]:
vote_2018_2022_sigungu['2018_vote_ratio'] = vote_2018_2022_sigungu['2018_total_vote']/vote_2018_2022_sigungu['2018_voter_all']
vote_2018_2022_sigungu['2022_vote_ratio'] = vote_2018_2022_sigungu['2022_total_vote']/vote_2018_2022_sigungu['2022_voter_all']

C:\Users\Popperkim\AppData\Local\Temp\ipykernel_5588\705497570.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vote_2018_2022_sigungu['2018_vote_ratio'] = vote_2018_2022_sigungu['2018_total_vote']/vote_2018_2022_sigungu['2018_voter_all']
C:\Users\Popperkim\AppData\Local\Temp\ipykernel_5588\705497570.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vote_2018_2022_sigungu['2022_vote_ratio'] = vote_2018_2022_sigungu['2022_total_vote']/vote_2018_2022_sigungu['2022_voter_all']

In [18]:
vote_2018_2022_sigungu.head()

,시도명,구시군명,2018_total_vote,outtotal_2018,outratio_2018,2022_total_vote,outtotal_2022,outratio_2022,2018_voter_all,2022_voter_all,2018_vote_ratio,2022_vote_ratio
0,서울특별시,종로구,81195.0,38884.0,0.485498,100629,53236.0,0.535757,134963.0,129968,0.601609,0.77426
1,서울특별시,중구,66474.0,31152.0,0.475668,84998,45940.0,0.545709,112336.0,111448,0.591743,0.76267
2,서울특별시,용산구,116054.0,60583.0,0.528362,152068,90619.0,0.601392,200009.0,199077,0.580244,0.763865
3,서울특별시,성동구,157863.0,71637.0,0.459606,197240,110827.0,0.567651,264634.0,252087,0.596533,0.782428
4,서울특별시,광진구,180373.0,78877.0,0.442215,235471,122996.0,0.528066,308174.0,303582,0.585296,0.775642

최종적으로 저장

In [16]:
vote_2018_2022_sigungu.to_excel("sigungu_vote_data.xlsx", index = False)

3. 교통 데이터 전처리

In [4]:
test_data_for_tran = pd.read_excel("접근가능인구비율_시군구.xlsx")[["HDCD_SD_NM", "HDCD_SGG_NM", "Mode_NM","Faci_NM","30분 이내"]]
test_data_for_tran = test_data_for_tran[test_data_for_tran["Mode_NM"]=="대중교통/도보"][["HDCD_SD_NM", "HDCD_SGG_NM","Faci_NM","30분 이내"]]

In [32]:
test_data_for_tran.columns

Index(['HDCD_SD_NM', 'HDCD_SGG_NM', 'Faci_NM', '30분 이내'], dtype='object')

In [5]:
test_data_for_tran["index"] = test_data_for_tran["HDCD_SD_NM"].astype('str') + "_" + test_data_for_tran["HDCD_SGG_NM"].astype('str')

In [6]:
test_data_for_tran.head()

  HDCD_SD_NM HDCD_SGG_NM Faci_NM  30분 이내      index
1      서울특별시         종로구    초등학교   100.0  서울특별시_종로구
3      서울특별시         종로구     중학교   100.0  서울특별시_종로구
5      서울특별시         종로구    고등학교   100.0  서울특별시_종로구
7      서울특별시         종로구  공공의료시설   100.0  서울특별시_종로구
9      서울특별시         종로구    병·의원   100.0  서울특별시_종로구

In [7]:
test_data_for_tran = test_data_for_tran.drop_duplicates(subset=['index', 'Faci_NM'])
test_data_for_tran = test_data_for_tran.pivot(index = 'index', columns="Faci_NM", values="30분 이내")

In [8]:
test_data_for_tran.head()

Faci_NM,고등학교,공공의료시설,공항,대규모점포,버스터미널,병·의원,전통시장,종합병원,중학교,철도역,초등학교
index,,,,,,,,,,,
강원도_강릉시,85.390913,69.839694,0.0,73.753724,56.182910,89.245756,82.523289,82.390410,89.308293,60.383979,98.121781
강원도_고성군,63.796477,83.810573,0.0,1.733562,62.134932,60.429923,47.915647,13.880731,78.823529,0.000000,85.076381
강원도_동해시,97.178683,83.434837,0.0,78.511228,73.476568,95.974143,96.375092,60.088606,98.412052,83.787859,98.834405
강원도_삼척시,74.909530,82.461400,0.0,52.471341,65.449377,79.241356,70.427786,56.221069,91.526662,13.169095,95.506870
강원도_속초시,98.773285,97.643201,0.0,97.088585,95.443949,98.409161,93.587970,95.232606,98.310139,0.000000,99.702529

In [102]:
test_data_for_tran.to_excel("data_for_tran.xlsx")

5. 합친 지역 데이터

- 데이터 참고
    - pop : 인구
    - ratio : 비율

In [39]:
pd.set_option('display.max_columns', 200)
region_all = pd.read_excel("Sigungu_semi_total.xlsx")
region_all.head()

,Unnamed: 0,total_pop,15-64_pop,65-_pop,남성_pop,내국인_pop,Forei_pop_rati,통근통학_total_pop,통근통학 -15_pop,통근통학 15-30_pop,통근통학 30-45_pop,통근통학 45-60_pop,통근통학 60-90_pop,통근통학 90-120_pop,통근통학 120-_pop,대학(4년제 미만)_pop,대학교(4년제 이상)_pop,대학원석사과정_pop,대학원박사과정_pop,고졸이하_pop,직종_관리자_pop,직종_전문가관련_pop,직종_사무_pop,직종_서비스_pop,직종_판매_pop,직종_농림어업숙련_pop,직종_기능원관련_pop,직종_장치기계조작조립_pop,직종_단순노무_pop,직종_기타_pop,"A.농업, 임업 및 어업_pop",B.광업_pop,C.제조업_pop,"D.전기,가스,증기 및공기조절 공급업_pop","E.수도, 하수 및 폐기물 처리, 원료 재생업_pop",F.건설업_pop,G.도매 및 소매업_pop,H.운수업 및 창고업_pop,I.숙박 및 음식점업_pop,J.정보통신업_pop,K.금융 및 보험업_pop,L.부동산업_pop,"M.전문,과학 및 기술 서비스업_pop","N.사업시설관리, 사업지원 및 임대서비스업_pop","O.공공행정,국방 및 사회보장 행정_pop",P.교육 서비스업_pop,Q.보건업 및 사회복지 서비스업_pop,"R.예술, 스포츠 및 여가관련 서비스업_pop","S.협회 및 단체, 수리 및 기타개인서비스업_pop",T.가구 내 고용활동 및 달리 분류되지 않은 자가소비 생산 활동_pop,U.국제 및 외국기관_pop,노후주택비율,30년 이상 노후주택,전체주택,사업체수,종사자수,도소매사업체수,도소매업종사자수,재정자립도(세입과목개편후),취업자,거주지내통근취업자,거주지외타지역통근취업자,경제활동인구,실업자,고용률,실업률,인구십만명당_문화기반시설수,문화기반시설수,주민등록인구,청년고용률_2022.1/2,청년고용률_2022.2/2,1인당_자동차등록대수,도로포장률,포장도로,전체개통도로,아파트매매2018.02,아파트매매2018.03,아파트매매2018.04,아파트매매2018.05,아파트매매2018.06,아파트매매2022.02,아파트매매2022.03,아파트매매2022.04,아파트월세2018.02,아파트월세2018.03,아파트월세2018.04,아파트월세2018.05,아파트월세2018.06,아파트월세2022.02,아파트월세2022.03,아파트월세2022.04,아파트전세2018.02,아파트전세2018.03,아파트전세2018.04,아파트전세2018.05,아파트전세2018.06,아파트전세2022.02,아파트전세2022.03,아파트전세2022.04,주택매매2018.02,주택매매2018.03,주택매매2018.04,주택매매2018.05,주택매매2018.06,주택매매2022.02,주택매매2022.03,주택매매2022.04,주택월세2018.02,주택월세2018.03,주택월세2018.04,주택월세2018.05,주택월세2018.06,주택월세2022.02,주택월세2022.03,주택월세2022.04,주택전세2018.03,주택전세2018.04,주택전세2018.05,주택전세2018.06,주택전세2018.07,주택전세2022.02,주택전세2022.03,주택전세2022.04,지역내총생산,순생산물세,총부가가치,농업어업임업_부가가치,광업_부가가치,제조업_부가가치,전기가스증기공기조절_부가가치,건설업_부가가치,도매소매업_부가가치,운수창고업_부가가치,숙박음식점업_부가가치,정보통신업_부가가치,금융보험업_부가가치,부동산업_부가가치,사업서비스업_부가가치,공공행정국방사회보장행정_부가가치,교육서비스업_부가가치,보건사회복지서비스업_부가가치,문화및기타서비스업_부가가치,고등학교_도보대중교통_30분_이내_pop_ratio,공공의료시설_도보대중교통_30분_이내_pop_ratio,공항_도보대중교통_30분_이내_pop_ratio,대규모점포_도보대중교통_30분_이내_pop_ratio,버스터미널_도보대중교통_30분_이내_pop_ratio,병·의원_도보대중교통_30분_이내_pop_ratio,전통시장_도보대중교통_30분_이내_pop_ratio,종합병원_도보대중교통_30분_이내_pop_ratio,중학교_도보대중교통_30분_이내_pop_ratio,철도역_도보대중교통_30분_이내_pop_ratio,초등학교_도보대중교통_30분_이내_pop_ratio,2018_total_투표수,야당_합계_2018,야당_비율_2018,2022_total_투표수,야당_합계_2022,야당_비율_2022,유입인구_2021,유출인구_2021,순이동_2021
0,서울 종로구,148857,111581,25859,71367,137913,0.073520,82692,16177,19880,25578,7890,10096,2949,122,11607,49976,11724,4884,1507,832,18806,18566,8951,10946,75,6639,2804,5646,330,39,21,8192,130,156,3028,13244,2195,7897,4137,4279,1913,5391,3333,3918,5573,5400,1969,2571,139,70,28.1,13198,46885,48361.0,275063.0,18683.0,46245.0,47.2,71800.0,29400.0,42400.0,81100.0,77800.0,3200.0,56100.0,47.0,68.0,144683.0,42.6,34.4,0.4,100.0,275177.0,275177.0,89.6,90.2,90.9,91.4,91.9,103.4,103.2,103.2,100.7,100.7,100.7,100.5,100.4,101.0,101.3,101.3,94.5,95.1,95.2,95.5,96.2,103.1,103.0,102.9,91.0,91.4,91.7,92.0,92.4,102.7,102.7,102.8,100.1,100.0,100.0,99.9,99.9,100.9,101.0,101.1,95.8,96.0,96.1,96.3,96.7,102.3,102.2,102.1,32427863.0,2760821.0,29669285.0,6595.0,473,586734.0,71734,349722.0,3049113,727172,594071.0,3751577.0,8635985.0,1694496.0,3396897.0,4317864.0,797974.0,1147496.0,624059.0,100.0,100.0,0.0,100.0,44.858894,100.0,100.0,99.092086,100.0,90.933885,100.0,81195.0,38884.0,0.485498,100629.0,53236.0,0.535757,22204.0,24428.0,-2224.0
1,서울 중구,126310,94276,22635,60657,114942,0.090001,68167,12584,16732,24717,5644,6475,1885,130,11517,39728,7198,2711,1208,585,13692,18807,7759,10913,51,5001,2962,5224,18,69,19,8101,149,135,2566,13886,2211,6561,3391,4391,1828,5150,2634,2586,3675,3872,1187,2368,189,44,17.9,7557,42319,70308.0,386564.0,32947.0,80600.0,55.3,67600.0,31300.0,36400.0,70200.0,67100.0,3000.0,55900.0,24.5,30.0,122499.0,42.4,45.8,0.5,100.0,114232.0,114232.0,87.7,88.9,89.5,90.1,90.6,103.4,103.3,103.2,100.4,100.4,100.4,100.4,100.4,102.1,102.3,102.6,95.5,95.7,95.6,95.6,95.6,103.5,103.3,103.2,89.0,89.7,90.2,90.6,91.1,102.6,102.6,102.6,100.2,100.2,100.2,100.2,100.2,101.2,101.3,101.5,97.0,96.9,96.9,96.9,97.0,102.4,102.3,102.2,52869673.0,4518207.0,48366658.0,15.0,38,1342700.0,82612,397132.0,7200998,1456679,1381363.0,6269239.0,19024669.0,1226985.0,5532496.0,2516361.0,606914.0,699262.0,598913.0,100.0,100.0,0.0,100.0,95.411327,100.0,100.0,100.000000,100.0,100.000000,100.0,66474.0,31152.0,0.475668,84998.0,45940.0,0.545709,19917.0,21126.0,-1209.0
2,서울 용산구,221688,165056,35692,106910,205288,0.073978,124078,18490,27727,46496,12167,14819,4256,123,18605,81942,18506,6601,1889,1418,28724,36389,14402,16170,102,6024,3724,8349,668,121,53,8909,179,210,4800,21582,4041,12373,7475,8081,3637,11195,5332,6124,7736,6724,2534,4094,348,422,29.7,22461,75739,29680.0,152605.0,10038.0,37238.0,41.7,119100.0,42600.0,76500.0,128900.0,122700.0,6200.0,59500.0,7.6,17.0,222953.0,47.0,49.3,0.3,100.0,281073.0,281073.0,89.2,90.5,90.9,91.3,91.5,105.6,105.5,105.7,99.3,99.3,99.3,99.3,99.3,101.7,102.0,102.4,93.9,94.0,94.0,94.0,94.0,103.9,103.7,103.6,88.2,89.0,89.4,89.8,90.1,103.9,104.0,104.1,99.8,99.8,99.8,99.8,99.8,100.8,101.0,101.2,96.1,96.1,96.1,96.1,96.1,102.2,102.1,102.0,11992461.0,968519.0,11024257.0,8268.0,0,130381.0,66614,459884.0,2135433,277231,455058.0,1570396.0,426554.0,1542589.0,1675789.0,1261938.0,349379.0,293687.0,413601.0,100.0,100.0,0.0,100.0,90.974017,100.0,100.0,100.000000,100.0,100.000000,100.0,116054.0,60583.0,0.528362,152068.0,90619.0,0.601392,36011.0,39572.0,-3561.0
3,서울 성동구,286469,213996,44996,139181,276273,0.035592,165458,24541,35418,65093,14513,19825,5872,196,27052,98352,19087,5302,2547,975,38676,42126,16512,21567,92,12113,7634,11740,66,151,26,15987,378,691,7773,29705,6028,13515,9144,10222,4951,13152,6479,5228,9771,9209,3147,5427,451,66,17.5,15969,91033,41665.0,203221.0,11731.0,41485.0,33.2,152700.0,53100.0,99500.0,154300.0,146700.0,7600.0,56400.0,5.2,15.0,285990.0,44.6,47.8,0.4,100.0,408339.0,408339.0,90.2,91.2,91.3,91.2,91.3,102.2,102.1,102.1,99.8,99.7,99.8,99.9,99.9,102.4,102.9,103.1,93.2,93.3,92.8,92.5,92.2,102.7,102.6,102.6,89.4,90.2,90.3,90.3,90.5,102.2,102.2,102.2,99.5,99.5,99.5,99.6,99.6,101.9,102.2,102.3,94.5,94.1,93.8,93.6,93.4,102.0,102.0,102.0,11419293.0,989499.0,10428677.0,290.0,-,1581602.0,81189,384636.0,1996929,285033,235008.0,1018229.0,183918.0,1321241.0,1712091.0,143713.0,758707.0,377983.0,371313.0,100.0,100.0,0.0,100.0,98.919850,100.0,100.0,100.000000,100.0,100.000000,100.0,157863.0,71637.0,0.459606,197240.0,110827.0,0.567651,39831.0,46075.0,-6244.0
4,서울 광진구,347099,267150,50562,166469,328395,0.053887,202218,30940,40768,71002,19635,31179,8091,603,39379,112589,17879,4558,2608,1117,49349,44245,25732,23330,283,15146,9791,16403,100,230,30,17492,278,445,11066,33176,7614,19045,11869,8775,5650,14904,9070,6332,12806,12850,4392,8757,687,28,20.0,18329,91432,33706.0,129707.0,9273.0,21953.0,26.1,188200.0,62400.0,125800.0,190400.0,183200.0,7300.0,57500.0,3.2,11.0,339996.0,50.8,52.3,0.3,100.0,324709.0,324709.0,90.6,91.8,92.2,92.5,92.4,102.0,101.9,101.9,101.5,101.5,101.6,101.7,101.8,101.0,100.8,101.8,95.3,95.3,95.2,94.8,94.7,102.7,102.6,102.6,91.0,91.5,91.8,92.0,92.1,101.9,101.9,101.9,100.7,100.7,100.7,100.8,100.8,100.6,100.6,101.1,96.0,95.9,95.8,95.7,95.5,102.1,102.0,102.0,6187957.0,452125.0,5735998.0,83.0,-,245215.0,80823,253820.0,809459,156441,431408.0,232945.0,211741.0,934055.0,720209.0,158993.0,660870.0,522308.0,324787.0,100.0,100.0,0.0,100.0,99.517006,100.0,100.0,99.829532,100.0,99.829532,100.0,180373.0,78877.0,0.442215,235471.0,122996.0,0.528066,51522.0,56750.0,-5228.0

In [43]:
print(region_all.columns.values)

['Unnamed: 0' 'total_pop' '15-64_pop' '65-_pop' '남성_pop' '내국인_pop'
 'Forei_pop_rati' '통근통학_total_pop' '통근통학 -15_pop' '통근통학 15-30_pop'
 '통근통학 30-45_pop' '통근통학 45-60_pop' '통근통학 60-90_pop' '통근통학 90-120_pop'
 '통근통학 120-_pop' '대학(4년제 미만)_pop' '대학교(4년제 이상)_pop' '대학원석사과정_pop'
 '대학원박사과정_pop' '고졸이하_pop' '직종_관리자_pop' '직종_전문가관련_pop' '직종_사무_pop'
 '직종_서비스_pop' '직종_판매_pop' '직종_농림어업숙련_pop' '직종_기능원관련_pop' '직종_장치기계조작조립_pop'
 '직종_단순노무_pop' '직종_기타_pop' 'A.농업, 임업 및 어업_pop' 'B.광업_pop' 'C.제조업_pop'
 'D.전기,가스,증기 및공기조절 공급업_pop' 'E.수도, 하수 및 폐기물 처리, 원료 재생업_pop' 'F.건설업_pop'
 'G.도매 및 소매업_pop' 'H.운수업 및 창고업_pop' 'I.숙박 및 음식점업_pop' 'J.정보통신업_pop'
 'K.금융 및 보험업_pop' 'L.부동산업_pop' 'M.전문,과학 및 기술 서비스업_pop'
 'N.사업시설관리, 사업지원 및 임대서비스업_pop' 'O.공공행정,국방 및 사회보장 행정_pop' 'P.교육 서비스업_pop'
 'Q.보건업 및 사회복지 서비스업_pop' 'R.예술, 스포츠 및 여가관련 서비스업_pop'
 'S.협회 및 단체, 수리 및 기타개인서비스업_pop' 'T.가구 내 고용활동 및 달리 분류되지 않은 자가소비 생산 활동_pop'
 'U.국제 및 외국기관_pop' '노후주택비율' '30년 이상 노후주택' '전체주택' '사업체수' '종사자수' '도소매사업체수'
 '도소매업종사자수' '재정자립도(세입과목개편후)' '취업자' '거주지내통근취업자' '거주지외타지역통근취업자' '경제활동인구'
 '실업자' '고용률' '실업률' '인구십만명당_문화기반시설수' '문화기반시설수' '주민등록인구' '청년고용률_2022.1/2'
 '청년고용률_2022.2/2' '1인당_자동차등록대수' '도로포장률' '포장도로' '전체개통도로' '아파트매매2018.02'
 '아파트매매2018.03' '아파트매매2018.04' '아파트매매2018.05' '아파트매매2018.06'
 '아파트매매2022.02' '아파트매매2022.03' '아파트매매2022.04' '아파트월세2018.02'
 '아파트월세2018.03' '아파트월세2018.04' '아파트월세2018.05' '아파트월세2018.06'
 '아파트월세2022.02' '아파트월세2022.03' '아파트월세2022.04' '아파트전세2018.02'
 '아파트전세2018.03' '아파트전세2018.04' '아파트전세2018.05' '아파트전세2018.06'
 '아파트전세2022.02' '아파트전세2022.03' '아파트전세2022.04' '주택매매2018.02' '주택매매2018.03'
 '주택매매2018.04' '주택매매2018.05' '주택매매2018.06' '주택매매2022.02' '주택매매2022.03'
 '주택매매2022.04' '주택월세2018.02' '주택월세2018.03' '주택월세2018.04' '주택월세2018.05'
 '주택월세2018.06' '주택월세2022.02' '주택월세2022.03' '주택월세2022.04' '주택전세2018.03'
 '주택전세2018.04' '주택전세2018.05' '주택전세2018.06' '주택전세2018.07' '주택전세2022.02'
 '주택전세2022.03' '주택전세2022.04' '지역내총생산' '순생산물세' '총부가가치' '농업어업임업_부가가치'
 '광업_부가가치' '제조업_부가가치' '전기가스증기공기조절_부가가치' '건설업_부가가치' '도매소매업_부가가치'
 '운수창고업_부가가치' '숙박음식점업_부가가치' '정보통신업_부가가치' '금융보험업_부가가치' '부동산업_부가가치'
 '사업서비스업_부가가치' '공공행정국방사회보장행정_부가가치' '교육서비스업_부가가치' '보건사회복지서비스업_부가가치'
 '문화및기타서비스업_부가가치' '고등학교_도보대중교통_30분_이내_pop_ratio'
 '공공의료시설_도보대중교통_30분_이내_pop_ratio' '공항_도보대중교통_30분_이내_pop_ratio'
 '대규모점포_도보대중교통_30분_이내_pop_ratio' '버스터미널_도보대중교통_30분_이내_pop_ratio'
 '병·의원_도보대중교통_30분_이내_pop_ratio' '전통시장_도보대중교통_30분_이내_pop_ratio'
 '종합병원_도보대중교통_30분_이내_pop_ratio' '중학교_도보대중교통_30분_이내_pop_ratio'
 '철도역_도보대중교통_30분_이내_pop_ratio' '초등학교_도보대중교통_30분_이내_pop_ratio'
 '2018_total_투표수' '야당_합계_2018' '야당_비율_2018' '2022_total_투표수' '야당_합계_2022'
 '야당_비율_2022' '유입인구_2021' '유출인구_2021' '순이동_2021']

6. 추가적인 데이터 Merging </br>

In [3]:
region_all_new = pd.read_excel('Re_t_new_merge.xlsx')

In [4]:
region_all_new.head()

,Unnamed: 0,특허건수_2019,특허건수_2020,특허건수_2021,노인천명당 노인여가복지시설수,녹지율,독거노인가구비율,빈집비율,걷기실천율,비만유병률,...,2018_투표자,야당_득표_2018,야당비율_2018,2022_투표자,야당득표_2022,야당비율_2022,2018_유권자,2022_유권자,2018_투표율,2022_투표율
0,서울종로구,1184,1279,1539,1.9,46.74,8.2,4.4,45.3,32.6,...,81195.0,38884.0,0.485498,100629.0,53236.0,0.535757,134963.0,129968.0,0.601609,0.774260
1,서울중구,1401,1584,1611,1.6,0.25,8.9,3.9,55.3,28.6,...,66474.0,31152.0,0.475668,84998.0,45940.0,0.545709,112336.0,111448.0,0.591743,0.762670
2,서울용산구,688,704,881,2.0,40.64,7.0,5.4,53.8,25.4,...,116054.0,60583.0,0.528362,152068.0,90619.0,0.601392,200009.0,199077.0,0.580244,0.763865
3,서울성동구,777,854,1066,2.6,25.78,6.5,2.4,51.3,30.7,...,157863.0,71637.0,0.459606,197240.0,110827.0,0.567651,264634.0,252087.0,0.596533,0.782428
4,서울광진구,548,599,593,1.4,30.89,5.8,1.2,55.8,29.1,...,180373.0,78877.0,0.442215,235471.0,122996.0,0.528066,308174.0,303582.0,0.585296,0.775642